/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_Fion_Account_Contact_Relatioa2sTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_Fion_Account_Contact_Relaa2sTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Fion_Account_Contact_Relationship__c());
    }
}