public inherited sharing class EthosUser {
  public String uid;
  public String name;
  public String mail;
  public String url;
  public String edit_url;
  public String last_access;
  public String last_login;
  public String created;
  public List<Integer> roles;
  public String status;
  public Profile_profile profile_profile;
  public String uuid;

  public class Profile_profile {
    public String uri;
    public String id;
    public String resource;
  }
}