/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_PagesApi_Community_Group_MemberTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_PagesApi_Community_Group_a0NTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new PagesApi__Community_Group_Member__c());
    }
}