public class EthosUserUpdateWrapper {
    
    public String field_custom_company;
    public String field_custom_dob;
    public String field_custom_employer_type;
    public String field_custom_job_role;
    public String field_custom_member_status;
    public String field_custom_member_type;
    public String field_custom_phone;
    public String field_custom_primary_position;
    public String field_custom_profession;
    public String field_custom_title;
    public String label;
	public String field_first_name;
    public String field_last_name;
    public FieldProfileLocation field_profile_location;

    public class FieldProfileLocation {
        public String street;
        public String city;
        public String province;
        public String postal_code;
        public String country;
        public String province_name;
        public String country_name;
    }
}