public class WHCourseWrapper {

    //public WHFieldAccmeData field_accme_data;
    public String field_course_rating_access;
    //public List<Object> uc_product_image;
    public Boolean field_course_catalog;
    //public FieldCourseCompletionMessage field_course_completion_message;
    //public FieldCourseDate field_course_date;
    //public List<Object> field_course_disclosure;
    //public FieldCourseEventDate field_course_event_date;
    //public List<Object> field_course_external_url;
    //public List<Object> field_course_format;
    //public WHFieldCourseImage field_course_image;
    //public FieldCourseIntro field_course_intro;
    public Boolean field_course_live;
    //public FieldCourseLocation field_course_location;
    //public Object field_course_password;
    //public List<Object> field_course_rating;
    //public List<Object> field_course_restrict_role;
    //public FieldCourseSummary field_course_summary;
    public Boolean field_course_transcript;
    //public FieldFacultyCredentials field_faculty_credentials;
    //public List<Object> field_hardware_software;
    //public FieldLearningObjectives field_learning_objectives;
    public Object field_requirements_max;
    public Object field_requirements_min;
    public Object field_show_child_catalog;
    public Object field_show_child_transcript;
    //public FieldTargetAudience field_target_audience;
    //public List<Object> upload;
    public Object field_enrollment_requirement_min;
    /* public List<Object> field_enrollment_requirements;
    public List<Object> field_accreditation;
    public List<Object> field_hotel_information;
    public List<Object> field_hotel_link;
    public List<Object> field_hotel_photo;
    public List<Object> field_hotel_travel;
    public List<Object> field_program;
    public List<Object> field_registration_instructions;
    public List<Object> field_venue_phone;
    public List<Object> field_course_category;
    public List<Object> field_related_courses;*/
    public Boolean field_show_on_calendar;
    //public List<Object> field_course_exhibitor;
    //public List<Object> field_course_qualifiers;
    public Object field_job_code;
    public Object field_primary_speciality;
    //public List<Object> field_course_image_cards;
    //public List<Object> field_income_expense;
    //public List<WHOgMembership> og_membership;
    /* public List<OgMembership> og_membership__1;
    public List<Object> og_membership__2;
    public List<Object> og_membership__3; */
    //public List<WHFlagCourseBookmarkUser> flag_course_bookmark_user;
    public String model;
    public String list_price;
    public String cost;
    public String sell_price;
    public String price;
    public String weight;
    public String weight_units;
    public String length;
    public String width;
    public String height;
    public String length_units;
    public String pkg_qty;
    public String ordering;
    public String shippable;
    public String nid;
    public String vid;
    public Boolean is_new;
    public String type;
    public String title;
    public String language;
    public String url;
    public String edit_url;
    public String status;
    public String promote;
    public String sticky;
    public String created;
    public String changed;
    //public WHAuthor author;
    
    public class FieldCourseCompletionMessage {
        public String value;
        public String format;
    }

    public class FieldCourseDate {
        public String value;
        public String value2;
        public Long duration;
    }

    public class FieldCourseEventDate {
        public String value;
        public String value2;
        public Long duration;
    }
    
    public class FieldCourseIntro {
        public String value;
        public String format;
    }

    public class FieldCourseLocation {
        public String lid;
        public String latitude;
        public String longitude;
        public String name;
        public String street;
        public String additional;
        public String city;
        public String province;
        public String postal_code;
        public String country;
        public String province_name;
        public String country_name;
        public Object phone;
        public Object fax;
        public Object email;
        public Object www;
    }

    public class FieldCourseSummary {
        public String value;
        public String summary;
        public String format;
    }

    public class FieldFacultyCredentials {
        public String value;
        public String format;
    }

    public class FieldLearningObjectives {
        public String value;
        public String format;
    }

    public class FieldTargetAudience {
        public String value;
        public String format;
    }

}