public class WHFieldAccmeData {
    
    public Boolean field_accme;
    public List<Object> field_accme_activity_duration;
    public Object field_accme_activity_id;
    public Object field_accme_activity_title;
    public Object field_accme_activity_type;
    public Object field_accme_city;
    public String field_accme_country;
    public Object field_accme_description;
    public Boolean field_accme_has_activity_id;
    public List<Object> field_accme_joint_sponsorship;
    public Object field_accme_provider_id;
    public String field_accme_sponsorship;
    public Object field_accme_state;
    public Boolean field_accme_support;
    public Object field_ama_learning_format;
    public List<Object> field_accme_boards;
    public Boolean field_accme_moc;
    public List<Object> field_accme_specialty;
    public Boolean field_accme_pars;
    public String field_accme_pars_create_date;
    public String field_accme_pars_update_date;
    public String field_accme_participation_fee;
    public Object field_accme_registration;
    public List<FieldAccmeCredits> field_accme_credits;
    public Object field_accme_pharm_activity_topic;
    public Object field_accme_pharm_activity_type;
    public List<Object> field_accme_pharmacy_dates;
    public List<Object> field_accme_profession;
    public List<Object> field_accme_abamco;
    public List<Object> field_accme_commendation_tags;
    public List<Object> field_accme_delivery_methods;
    public Boolean field_accme_for_public_list;
    public Object field_accme_is_interprofessional;
    public List<Object> field_accme_measured_outcomes;
    public Object field_accme_mips;
    public Object field_accme_postal_code;
    public Object field_accme_credit_claim_date;
    public String id;
    public String type;
    public String title;
    public String changed;
    public Object feeds_item_guid;
    public Object feeds_item_url;
    public Object feed_nid;
    
    public class FieldAccmeCredits {
        public String uri;
        public String id;
        public String resource;
        public String uuid;
    }
}